[package]
name = "polars_ds"
version = "0.1.0"
edition = "2021"

[lib]
name = "_polars_ds"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = {version = "0.20", features = ["extension-module"]}
pyo3-polars = {version = "0.8", features = ["derive"]}
polars = {version = "0.34", features = ["fmt", "performant", "chunked_ids", "lazy","random", "dtype-struct", "ndarray"]}
polars-core = "0.34"
polars-lazy = "0.34"
num = "0.4.1"
faer = {version = "0.14.1", features = ["ndarray"]}
ndarray = "0.15.6"
serde = { version = "1.0.190", features = ["derive"] }

[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }
